/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for INDefault
 */
public class INDefaultTest {
    private final INDefault model = new INDefault();

    /**
     * Model tests for INDefault
     */
    @Test
    public void testINDefault() {
        // TODO: test INDefault
    }

    /**
     * Test the property 'thresh'
     */
    @Test
    public void threshTest() {
        // TODO: test thresh
    }

    /**
     * Test the property 'grey'
     */
    @Test
    public void greyTest() {
        // TODO: test grey
    }

}
