/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for INObject
 */
public class INObjectTest {
    private final INObject model = new INObject();

    /**
     * Model tests for INObject
     */
    @Test
    public void testINObject() {
        // TODO: test INObject
    }

    /**
     * Test the property 'inClass'
     */
    @Test
    public void inClassTest() {
        // TODO: test inClass
    }

    /**
     * Test the property 'y0'
     */
    @Test
    public void y0Test() {
        // TODO: test y0
    }

    /**
     * Test the property 'x0'
     */
    @Test
    public void x0Test() {
        // TODO: test x0
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

}
