/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.irisnet.java.client.model.INDefault;
import de.irisnet.java.client.model.INParam;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for INParams
 */
public class INParamsTest {
    private final INParams model = new INParams();

    /**
     * Model tests for INParams
     */
    @Test
    public void testINParams() {
        // TODO: test INParams
    }

    /**
     * Test the property 'inDefault'
     */
    @Test
    public void inDefaultTest() {
        // TODO: test inDefault
    }

    /**
     * Test the property 'inParam'
     */
    @Test
    public void inParamTest() {
        // TODO: test inParam
    }

}
