/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for INParam
 */
public class INParamTest {
    private final INParam model = new INParam();

    /**
     * Model tests for INParam
     */
    @Test
    public void testINParam() {
        // TODO: test INParam
    }

    /**
     * Test the property 'inClass'
     */
    @Test
    public void inClassTest() {
        // TODO: test inClass
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'drawMode'
     */
    @Test
    public void drawModeTest() {
        // TODO: test drawMode
    }

    /**
     * Test the property 'grey'
     */
    @Test
    public void greyTest() {
        // TODO: test grey
    }

}
