/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.irisnet.java.client.model.INObject;
import de.irisnet.java.client.model.INRule;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IrisNet
 */
public class IrisNetTest {
    private final IrisNet model = new IrisNet();

    /**
     * Model tests for IrisNet
     */
    @Test
    public void testIrisNet() {
        // TODO: test IrisNet
    }

    /**
     * Test the property 'rulesBroken'
     */
    @Test
    public void rulesBrokenTest() {
        // TODO: test rulesBroken
    }

    /**
     * Test the property 'helpSuggested'
     */
    @Test
    public void helpSuggestedTest() {
        // TODO: test helpSuggested
    }

    /**
     * Test the property 'getnObjects'
     */
    @Test
    public void getnObjectsTest() {
        // TODO: test getnObjects
    }

    /**
     * Test the property 'getnClasses'
     */
    @Test
    public void getnClassesTest() {
        // TODO: test getnClasses
    }

    /**
     * Test the property 'inRule'
     */
    @Test
    public void inRuleTest() {
        // TODO: test inRule
    }

    /**
     * Test the property 'inObject'
     */
    @Test
    public void inObjectTest() {
        // TODO: test inObject
    }

}
