/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LicenseInfo
 */
public class LicenseInfoTest {
    private final LicenseInfo model = new LicenseInfo();

    /**
     * Model tests for LicenseInfo
     */
    @Test
    public void testLicenseInfo() {
        // TODO: test LicenseInfo
    }

    /**
     * Test the property 'creditsUsed'
     */
    @Test
    public void creditsUsedTest() {
        // TODO: test creditsUsed
    }

    /**
     * Test the property 'creditsRemaining'
     */
    @Test
    public void creditsRemainingTest() {
        // TODO: test creditsRemaining
    }

    /**
     * Test the property 'totalCredits'
     */
    @Test
    public void totalCreditsTest() {
        // TODO: test totalCredits
    }

}
