/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.irisnet.java.client.model.INDefault;
import de.irisnet.java.client.model.INParam;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A set of parameters/rules that describe how the AI should behave.
 */
@ApiModel(description = "A set of parameters/rules that describe how the AI should behave.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-22T13:03:14.380+02:00[Europe/Berlin]")
public class INParams {
  public static final String SERIALIZED_NAME_IN_DEFAULT = "inDefault";
  @SerializedName(SERIALIZED_NAME_IN_DEFAULT)
  private INDefault inDefault;

  public static final String SERIALIZED_NAME_IN_PARAM = "inParam";
  @SerializedName(SERIALIZED_NAME_IN_PARAM)
  private List<INParam> inParam = null;


  public INParams inDefault(INDefault inDefault) {
    
    this.inDefault = inDefault;
    return this;
  }

   /**
   * Get inDefault
   * @return inDefault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public INDefault getInDefault() {
    return inDefault;
  }


  public void setInDefault(INDefault inDefault) {
    this.inDefault = inDefault;
  }


  public INParams inParam(List<INParam> inParam) {
    
    this.inParam = inParam;
    return this;
  }

  public INParams addInParamItem(INParam inParamItem) {
    if (this.inParam == null) {
      this.inParam = new ArrayList<INParam>();
    }
    this.inParam.add(inParamItem);
    return this;
  }

   /**
   * A list of parameter sets that describe the rules of the objects.
   * @return inParam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of parameter sets that describe the rules of the objects.")

  public List<INParam> getInParam() {
    return inParam;
  }


  public void setInParam(List<INParam> inParam) {
    this.inParam = inParam;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    INParams inParams = (INParams) o;
    return Objects.equals(this.inDefault, inParams.inDefault) &&
        Objects.equals(this.inParam, inParams.inParam);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inDefault, inParam);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class INParams {\n");
    sb.append("    inDefault: ").append(toIndentedString(inDefault)).append("\n");
    sb.append("    inParam: ").append(toIndentedString(inParam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

