/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in realtime.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client;

import de.irisnet.java.ApiException;
import de.irisnet.java.client.model.Error;
import de.irisnet.java.client.model.LicenseInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LicenseKeyOperationsApi
 */
@Ignore
public class LicenseKeyOperationsApiTest {

    private final LicenseKeyOperationsApi api = new LicenseKeyOperationsApi();

    
    /**
     * Get the cost of the previously set parameters. The cost of the configuration is subtracted from the license key during each check.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAICostTest() throws ApiException {
        Long response = api.getAICost();

        // TODO: test validations
    }
    
    /**
     * Get information from given license key.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLicenseInfoTest() throws ApiException {
        String licenseKey = null;
        LicenseInfo response = api.getLicenseInfo(licenseKey);

        // TODO: test validations
    }
    
}
